name: Build Halium Boot for Lava Blaze

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y abootimg android-sdk-libsparse-utils mkbootimg unzip

   - name: Build halium-boot.img
      run: |
        mkdir halium
        cp boot.img halium/
        cp vendor.img halium/
        cp dtbo.img halium/
        cp vbmeta.img halium/
        cd halium
        mkdir output

        # Dummy logic - replace with actual halium-boot build if source available
        dd if=/dev/zero of=output/halium-boot-lava.img bs=1M count=32

    - name: Upload boot image
      uses: actions/upload-artifact@v3
      with:
        name: halium-boot-lava
        path: halium/output/halium-boot-lava.img
