name: Build halium-boot

on:
  workflow_dispatch:

jobs:
  build-halium-boot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up tools
        run: |
          sudo apt update
          sudo apt install -y abootimg android-sdk-libsparse-utils mkbootimg

      - name: Prepare halium directory
        run: |
          mkdir -p halium/output

      - name: Download image files
        run: |
          wget -O halium/boot.img "https://drive.google.com/file/d/1AHb1yBO5nzoXDKzOOGje9n01GjsGvfpb/view?usp=drive_link"
          wget -O halium/vendor.img "https://drive.google.com/file/d/18xOuo6Ez3agdVbY59Ilq5TLtJSaBbgoP/view?usp=drive_link"
          wget -O halium/vbmeta.img "https://drive.google.com/file/d/1pVuEf35Rjcwz6jydP5-LMIH1OVwnBav9/view?usp=drive_link"
          wget -O halium/dtbo.img "https://drive.google.com/file/d/1fxR-TRPX2LzzxjQ_nYoxSdQ2O0LemFmf/view?usp=drive_link"

      - name: Dummy build halium-boot.img (replace with real logic)
        run: |
          dd if=/dev/zero of=halium/output/halium-boot-lava.img bs=1M count=32

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: halium-boot-lava
          path: halium/output/halium-boot-lava.img
